USE DATABASE ORDER_DB;
USE SCHEMA GOLD;

-- Create customer dimension table
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID       NUMBER PRIMARY KEY AUTOINCREMENT,
    CUSTOMER_NAME     STRING,
    ETL_TIMESTAMP     TIMESTAMP_NTZ
);

-- Create item dimension table
CREATE OR REPLACE TABLE DIM_ITEM
(
    ITEM_ID           NUMBER PRIMARY KEY AUTOINCREMENT,
    ITEM_TYPE         STRING,
    ETL_TIMESTAMP     TIMESTAMP_NTZ
);

-- Create region dimension table
CREATE OR REPLACE TABLE DIM_REGION
(
    REGION_ID         NUMBER PRIMARY KEY AUTOINCREMENT,
    REGION            STRING,
    ETL_TIMESTAMP     TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DIM_DATE
(
    DATE              DATE PRIMARY KEY,
    YEAR              NUMBER,
    MONTH             NUMBER,
    MONTH_NAME        STRING,
    DAY               NUMBER
);

INSERT INTO DIM_DATE
SELECT
    CAST(DATE_VALUE AS DATE) AS DATE,
    YEAR(DATE_VALUE) AS YEAR,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    DAY(DATE_VALUE) AS DAY
FROM
(
    SELECT
    DATEADD(
        DAY,
        SEQ4(),
        '2024-01-01'
    ) AS DATE_VALUE
FROM TABLE(GENERATOR(ROWCOUNT => 1096))
) TAB;

CREATE OR REPLACE TABLE FACT_ORDERS
(
    ORDER_ID          NUMBER,
    ORDER_DATE        DATE,
    DELIVERY_DATE     DATE,

    CUSTOMER_ID       NUMBER,
    ITEM_ID           NUMBER,
    REGION_ID         NUMBER,

    QUANTITY          NUMBER,
    UNIT_PRICE        NUMBER(10,2),
    DISCOUNT          NUMBER(5,2),
    SALES_AMOUNT      NUMBER(12,2),

    DELIVERY_DAYS     NUMBER,

    ORDER_STATUS      STRING,
    SHIPPING_METHOD   STRING,

    SOURCE_FILE_NAME  STRING,
    ETL_TIMESTAMP     TIMESTAMP_NTZ
);






