-- Create the silver stream
USE DATABASE ORDER_DB;
USE SCHEMA SILVER;
CREATE OR REPLACE STREAM CUSTOMER_ORDERS_CLEAN_STREAM
ON TABLE CUSTOMER_ORDERS_CLEAN;

-- Create the silver task
USE DATABASE ORDER_DB;
USE SCHEMA TASK;

CREATE OR REPLACE TASK TASK_SILVER_LOAD
    WAREHOUSE = ORDER_WH
    AFTER TASK_BRONZE_LOAD
    WHEN SYSTEM$STREAM_HAS_DATA('BRONZE.CUSTOMER_ORDERS_RAW_STREAM')
AS
CALL SILVER.PROC_SILVER_LOAD();

-- Resume the task
ALTER TASK TASK_SILVER_LOAD RESUME;