-- Create the Warehouse
CREATE OR REPLACE WAREHOUSE ORDER_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create database
CREATE OR REPLACE DATABASE ORDER_DB;

-- Create three schemas
USE DATABASE ORDER_DB;

CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;
CREATE OR REPLACE SCHEMA TASK;
