USE DATABASE ORDER_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE PROCEDURE PROC_GOLD_LOAD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Read stream once into a temporary table
    CREATE OR REPLACE TEMP TABLE TMP_GOLD_BATCH AS
    SELECT *
    FROM SILVER.CUSTOMER_ORDERS_CLEAN_STREAM;

    -- Load Customer Dimension
    MERGE INTO DIM_CUSTOMER AS T
    USING
    (
        SELECT DISTINCT
            CUSTOMER_NAME,
            CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
        FROM TMP_GOLD_BATCH
        WHERE CUSTOMER_NAME IS NOT NULL
    ) S
    ON T.CUSTOMER_NAME = S.CUSTOMER_NAME

    WHEN NOT MATCHED THEN
    INSERT
    (CUSTOMER_NAME, ETL_TIMESTAMP)
    VALUES
    (S.CUSTOMER_NAME, S.ETL_TIMESTAMP);

    -- Load Item Dimension
    MERGE INTO DIM_ITEM AS T
    USING
    (
        SELECT DISTINCT
            ITEM_TYPE,
            CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
        FROM TMP_GOLD_BATCH
        WHERE ITEM_TYPE IS NOT NULL
    ) S
    ON T.ITEM_TYPE = S.ITEM_TYPE

    WHEN NOT MATCHED THEN
    INSERT(ITEM_TYPE, ETL_TIMESTAMP)
    VALUES
    (S.ITEM_TYPE, S.ETL_TIMESTAMP);

    -- Load Region Dimension
    MERGE INTO DIM_REGION AS T
    USING
    (
        SELECT DISTINCT
            REGION,
            CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
        FROM TMP_GOLD_BATCH
        WHERE REGION IS NOT NULL
    ) S
    ON T.REGION = S.REGION

    WHEN NOT MATCHED THEN
    INSERT
    (REGION, ETL_TIMESTAMP)
    VALUES
    (S.REGION, S.ETL_TIMESTAMP);

    -- Load Fact Table
   
    MERGE INTO FACT_ORDERS AS T
    USING
    (
        SELECT
            S.ORDER_ID,
            S.ORDER_DATE,
            S.DELIVERY_DATE,

            C.CUSTOMER_ID,
            I.ITEM_ID,
            R.REGION_ID,

            S.QUANTITY,
            S.UNIT_PRICE,
            S.DISCOUNT,
            (S.QUANTITY * S.UNIT_PRICE) * (1 - S.DISCOUNT) AS SALES_AMOUNT,

            S.DELIVERY_DAYS,
            S.ORDER_STATUS,
            S.SHIPPING_METHOD,
            S.SOURCE_FILE_NAME,
            CURRENT_TIMESTAMP() AS ETL_TIMESTAMP

        FROM TMP_GOLD_BATCH S
        INNER JOIN DIM_CUSTOMER C ON S.CUSTOMER_NAME = C.CUSTOMER_NAME
        INNER JOIN DIM_ITEM I ON S.ITEM_TYPE = I.ITEM_TYPE
        INNER JOIN DIM_REGION R ON S.REGION = R.REGION
    ) SRC
    ON T.ORDER_ID = SRC.ORDER_ID

    WHEN NOT MATCHED THEN
    INSERT
    (ORDER_ID, ORDER_DATE, DELIVERY_DATE, CUSTOMER_ID, ITEM_ID, REGION_ID, QUANTITY,
     UNIT_PRICE, DISCOUNT, SALES_AMOUNT, DELIVERY_DAYS, ORDER_STATUS, SHIPPING_METHOD,
     SOURCE_FILE_NAME, ETL_TIMESTAMP
    )
    VALUES
    (SRC.ORDER_ID, SRC.ORDER_DATE, SRC.DELIVERY_DATE, SRC.CUSTOMER_ID, SRC.ITEM_ID,
     SRC.REGION_ID, SRC.QUANTITY, SRC.UNIT_PRICE, SRC.DISCOUNT, SRC.SALES_AMOUNT,
     SRC.DELIVERY_DAYS, SRC.ORDER_STATUS, SRC.SHIPPING_METHOD, SRC.SOURCE_FILE_NAME,
     SRC.ETL_TIMESTAMP);

    RETURN 'Gold layer loaded successfully.';

END;
$$;