-- Create a Task to execute the GOLD load procedure
USE DATABASE ORDER_DB;
USE SCHEMA TASK;

CREATE OR REPLACE TASK TASK_GOLD_LOAD
WAREHOUSE = ORDER_WH
AFTER TASK.TASK_SILVER_LOAD
    WHEN SYSTEM$STREAM_HAS_DATA('ORDER_DB.SILVER.CUSTOMER_ORDERS_CLEAN_STREAM')
AS
CALL GOLD.PROC_GOLD_LOAD();

-- Resume the task
ALTER TASK TASK_GOLD_LOAD RESUME;
