-- Create the File Format
USE DATABASE ORDER_DB;
USE SCHEMA BRONZE;

-- Create storage integration
CREATE OR REPLACE STORAGE INTEGRATION ORDER_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::824939473734:role/SnowflakePipeS3ReadWriteRole'
STORAGE_ALLOWED_LOCATIONS = ('s3://rukky-order-lake/');

DESC STORAGE INTEGRATION ORDER_S3_INT;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL','null','');

-- Create the stage
CREATE OR REPLACE STAGE ORDER_STAGE
URL = 's3://rukky-order-lake/'
STORAGE_INTEGRATION = ORDER_S3_INT
FILE_FORMAT = CSV_FILE_FORMAT;



