USE DATABASE ORDER_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TRANSIENT TABLE CUSTOMER_ORDERS_RAW
(
    ORDER_ID           NUMBER,
    CUSTOMER_NAME      STRING,
    ORDER_DATE         DATE,
    DELIVERY_DATE      DATE,
    ITEM_TYPE          STRING,
    QUANTITY           NUMBER,
    ORDER_STATUS       STRING,
    SHIPPING_METHOD    STRING,
    UNIT_PRICE         NUMBER(10,2),
    REGION             STRING,
    DISCOUNT           NUMBER(5,2),

    SOURCE_FILE_NAME   STRING,
    LOAD_TIMESTAMP     TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);