-- Create a stream to capture changes in the bronze table
USE DATABASE ORDER_DB;
USE SCHEMA BRONZE;


CREATE OR REPLACE STREAM CUSTOMER_ORDERS_RAW_STREAM
ON TABLE CUSTOMER_ORDERS_RAW
APPEND_ONLY = TRUE;


-- Create a Task to execute the bronze load procedure
USE DATABASE ORDER_DB;
USE SCHEMA TASK;

CREATE OR REPLACE TASK TASK_BRONZE_LOAD
WAREHOUSE = ORDER_WH
SCHEDULE = '5 MINUTE'  -- runs every 1 minute
AS
CALL BRONZE.PROC_BRONZE_LOAD();

-- Resume the task
ALTER TASK TASK_BRONZE_LOAD suspend;


