USE DATABASE ORDER_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE TRANSIENT TABLE CUSTOMER_ORDERS_CLEAN
(
    ORDER_ID           NUMBER,
    CUSTOMER_NAME      STRING,
    ORDER_DATE         DATE,
    DELIVERY_DATE      DATE,
    ITEM_TYPE          STRING,
    QUANTITY           NUMBER,
    ORDER_STATUS       STRING,
    SHIPPING_METHOD    STRING,
    UNIT_PRICE         NUMBER(10,2),
    REGION             STRING,
    DISCOUNT           NUMBER(5,2),

    DELIVERY_DAYS      NUMBER,

    SOURCE_FILE_NAME   STRING,
    ETL_TIMESTAMP      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);