USE DATABASE ORDER_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE PROCEDURE PROC_SILVER_LOAD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    MERGE INTO CUSTOMER_ORDERS_CLEAN AS T
    USING
    (
        SELECT
            ORDER_ID,
            TRIM(CUSTOMER_NAME) AS CUSTOMER_NAME,
            ORDER_DATE,
            DELIVERY_DATE,
            UPPER(TRIM(ITEM_TYPE)) AS ITEM_TYPE,
            QUANTITY,
            INITCAP(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
            INITCAP(TRIM(SHIPPING_METHOD)) AS SHIPPING_METHOD,
            UNIT_PRICE,
            UPPER(TRIM(REGION)) AS REGION,
            DISCOUNT,
            CASE
            WHEN DELIVERY_DATE IS NULL THEN NULL
            ELSE DATEDIFF('DAY', ORDER_DATE, DELIVERY_DATE)
            END AS DELIVERY_DAYS,
            SOURCE_FILE_NAME,
            CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
        FROM BRONZE.CUSTOMER_ORDERS_RAW_STREAM
        WHERE
            ORDER_ID IS NOT NULL
            AND QUANTITY > 0
            AND UNIT_PRICE > 0
            AND DISCOUNT >= 0
    ) S
    ON T.ORDER_ID = S.ORDER_ID

    WHEN MATCHED THEN
        UPDATE SET
            T.CUSTOMER_NAME    = S.CUSTOMER_NAME,
            T.ORDER_DATE       = S.ORDER_DATE,
            T.DELIVERY_DATE    = S.DELIVERY_DATE,
            T.ITEM_TYPE        = S.ITEM_TYPE,
            T.QUANTITY         = S.QUANTITY,
            T.ORDER_STATUS     = S.ORDER_STATUS,
            T.SHIPPING_METHOD  = S.SHIPPING_METHOD,
            T.UNIT_PRICE       = S.UNIT_PRICE,
            T.REGION           = S.REGION,
            T.DISCOUNT         = S.DISCOUNT,
            T.DELIVERY_DAYS    = S.DELIVERY_DAYS,
            T.SOURCE_FILE_NAME = S.SOURCE_FILE_NAME,
            T.ETL_TIMESTAMP    = S.ETL_TIMESTAMP

    WHEN NOT MATCHED THEN
        INSERT
        (
            ORDER_ID, CUSTOMER_NAME, ORDER_DATE, DELIVERY_DATE, ITEM_TYPE,
            QUANTITY, ORDER_STATUS, SHIPPING_METHOD, UNIT_PRICE, REGION,
            DISCOUNT, DELIVERY_DAYS, SOURCE_FILE_NAME, ETL_TIMESTAMP
        )
        VALUES
        (
            S.ORDER_ID, S.CUSTOMER_NAME, S.ORDER_DATE, S.DELIVERY_DATE, S.ITEM_TYPE,
            S.QUANTITY, S.ORDER_STATUS, S.SHIPPING_METHOD, S.UNIT_PRICE, S.REGION,
            S.DISCOUNT, S.DELIVERY_DAYS, S.SOURCE_FILE_NAME, S.ETL_TIMESTAMP
        );

    RETURN 'Silver layer loaded successfully.';
END;
$$;